export const ROUTES = {
  HOME: '/',
  BUY: '/buy',
  CAGES: '/cages',
  CAGE_FRONT: '/cage-front',
  CAGE_LITTLE: '/cage-little',
  CAGE_VOLUME: '/cage-volume',
  TOP_CAPS: '/top-caps',
  FEEDBAG_HANGER: '/feedbag-hanger',
  CHAIN_BREAKER: '/chain-breaker',
  VOILE_STRAP: '/voile-strap',
  ITCHY_AND_SCRATCHY: '/itchy-and-scratchy',
  MERCH: '/merch',
  TEST_RIDE: '/test-ride',
};